// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1Cdi5Sb0Zpqpm6o4-D2DhEYTF9V8tpo',
    appId: '1:677656704148:web:2af4da80e2901cb7c6f081',
    messagingSenderId: '677656704148',
    projectId: 'wordcraft-69dae',
    authDomain: 'wordcraft-69dae.firebaseapp.com',
    storageBucket: 'wordcraft-69dae.appspot.com',
    measurementId: 'G-9ERCSV9C9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Ksu6v60gySIo39SwRxiSuWVzV0PrcB8',
    appId: '1:677656704148:android:6a1559962c5fc0f5c6f081',
    messagingSenderId: '677656704148',
    projectId: 'wordcraft-69dae',
    storageBucket: 'wordcraft-69dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFEVfJrKiWhwCG60GWEStX_m6a1Mxr20',
    appId: '1:677656704148:ios:09c2b92dc6a2e8aac6f081',
    messagingSenderId: '677656704148',
    projectId: 'wordcraft-69dae',
    storageBucket: 'wordcraft-69dae.appspot.com',
    iosBundleId: 'com.example.languagelearningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUFEVfJrKiWhwCG60GWEStX_m6a1Mxr20',
    appId: '1:677656704148:ios:a4a58c30aa390b48c6f081',
    messagingSenderId: '677656704148',
    projectId: 'wordcraft-69dae',
    storageBucket: 'wordcraft-69dae.appspot.com',
    iosBundleId: 'com.example.languagelearningapp.RunnerTests',
  );
}
